CREATE  TABLE Person (
  person_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR2(50),
  last_name VARCHAR2(60),
  mail_id VARCHAR2(100),
  address VARCHAR2(500)
);

INSERT INTO Person (first_name,last_name,mail_id,address) values ('Thej','Karuneegar','kishores1984@gmail.com','800 S Wells Street , Apt 1114,Chicago - IL 60607');